---
title: "Testing Synthetic DiD Version 1"
author: "Morgan Bale"
date: "8/24/2022"
output: 
  github_document:
    toc: true 
---

```{r opts, echo=FALSE}
library(tidyverse)
library(rstan)
library(bayesplot)
library(gtools)

rstan_options(auto_write=TRUE)
options(mc.cores=parallel::detectCores()-1)

knitr::opts_chunk$set(fig.path="../Figures/bscm/")
```

# Data 

Create synthetic data to test model. 
```{r}
N <- 20 #total num stores
C <- 10 #num control stores 
TT <- 100 # pre period ends at t=50 
I <- 50 #intervention time 

#create parameters 
alpha <- rnorm(N)
gamma_pre <- rnorm(TT/2, mean=1, sd=4)
gamma_post <- rnorm(TT/2, mean=2, sd=4)
gamma <- c(gamma_pre, gamma_post)
tau <- 2

#create indicator D
D <- matrix(NA, nrow=N, ncol=TT) 

for(n in 1:N) {
  for(t in 1:TT) {
    if(n > C & t > I) {D[n,t]=1}
    else {D[n,t]=0}
  }
}

#make Y 
Y <- matrix(NA, nrow=N, ncol=TT) 
for(n in 1:N) {
  for(t in 1:TT) {
    Y[n,t] = alpha[n] + gamma[t] + D[n,t]*tau
  }
}

#check Y plot
as_tibble(t(Y)) %>% gather(key="store", value="Y") %>% mutate(week=rep(1:TT, times=N)) %>% ggplot(aes(x=week, y=Y, col=as.factor(store))) + geom_line() + geom_vline(xintercept=I)

#put in list for stan
d <- list(N=N, TT=TT, I=I, C=C, D=D, Y=Y, alpha=alpha, gamma=gamma, tau=tau)
```

# Model

```{r}
model <- stan_model(file="../Code/Model/sdid_v1.stan")
print(model)

draws <- sampling(model, data=d, seed=2020)
```

# Results 

## Traceplots

```{r}
traceplot(draws, pars="alpha")
traceplot(draws, pars="tau")
traceplot(draws, pars="sigma")
traceplot(draws, pars="gamma[1]")
```

## Histograms 

```{r}
mcmc_recover_hist(As.mcmc.list(draws, pars="tau"), true=d$tau)
mcmc_recover_hist(As.mcmc.list(draws, pars="alpha"), true=as.vector(d$alpha))
```

## Sales plots 

```{r}

```

